### ISSUE TITLE
TODO: Version 0.1.0

### ISSUE THREAD

**Issue by Sandertv** [Sandertv/BlockSniper#1]
**TODO list for the version 0.1.0 update.**

**Multi-language**
- [x] Add a multi-language system.
- [x] Add English translation, and Dutch.

**New shapes**
- [x] Implement standing cylinders.
- [x] Implement cuboids. (Real cuboids, not actual cubes)

**New types**
- [x] Implement flatten.
- [x] Implement clean.
- [x] Implement drain.
- [x] Implement leaf blower.

**New commands**
- [x] Implement undo.
- [x] Add BlockSniper command.

**Configuration**
- [x] Add an actual settings.yml instead of an empty file.
- [x] Make some things like max radius configurable.

**Bug fixes**
Currently no known bugs.

Feel free to leave any suggestions below.

**Comment by RTGNetworkkk** [comment]
Nice :)

**Comment by Sandertv** [comment]
Thanks! :)

**Comment by Sandertv** [comment]
I moved two things for the next release. The plugin is ready for release 0.1.0! Hurray!
