### ISSUE TITLE
TODO: Version 1.0.0

### ISSUE THREAD

**Issue by Sandertv** [Sandertv/BlockSniper#17]
TODO list for the 1.0.0 update.

**Command changes**
- [x] Change BrushWand command to Brush.
- [x] Make Brush more user friendly, with easier sub commands.
- [x] Remove Snipe command.

**Types and Shapes changes**
- [x] Make types be executable on any shape.
- [x] Move lots of code for optimization.

**Brush changes**
- [x] Make Brush a specified item. (Arrow, blaze rod, etc.)
- [x] Remove Brush wand enabling / disabling.

**Optimizations**
- [x] Optimize Brush command/usage.
- [x] Optimize selecting of shapes and types.

**Bug fixes**
- [ ] As always, fix every issue that might show up.

**Wiki**
- [x] Add a super-detailed wiki with every information that is possible in the plugin.

Again, feel free to leave suggestions for the 1.0.0 update!

**Comment by opkiler22789** [comment]
Excellent! forward to translating into reality

**Comment by Sandertv** [comment]
Yup! :)

**Comment by Sandertv** [comment]
Update 1.0.0 is arriving faster than I expected, so there might be a couple more features hidden here and there :)

**Comment by MrKiaN** [comment]
WoW This Is Nice, Its Work Nice For Mee!!

**Comment by Sandertv** [comment]
Great too hear you're enjoying the plugin so far :)

**Comment by Sandertv** [comment]
Version 1.0.0 Released! Make sure to check out the new Wiki for detailed information!
