### ISSUE TITLE
TODO: Version 1.1.0

### ISSUE THREAD

**Issue by Sandertv** [Sandertv/BlockSniper#25]
TODO list for the 1.1.0 update.

**New Types**
- [x] Add CleanEntities brush type.
- [x] Add Biome brush type.

**New Brush Parameters**
- [x] Add Decrementing brush.
- [x] Add Biome brush.

**Configuration**
- [x] Make Brush item configurable.
- [x] Make either resetting, or remaining at the same size with decrementing brush configurable.

**Copy -> Paste**
- [x] Implement undo for pasting templates and copies.

**API**
- [x] Add BrushPropertiesChangeEvent.

**Bug Fixes**
- [x] Fix Undo destroying management.
- [x] Fix multiworld Copying.

**Comment by Sandertv** [comment]
Almost there! Just the gravity brush is very hard. getHighestBlockAt() from PocketMine does not seem to work correctly.
